In [1]:
import numpy as np 
import pandas as pd

In [2]:
myindex = ['김구', '이봉창', '안중근', '윤봉길']
mycolumns = ['강남구', '은평구', '마포구', '용산구']
mylist = list( 10 * onedata for onedata in range(1, 17))
myframe = pd.DataFrame( np.reshape(mylist, (4, 4)), index=myindex, columns = mycolumns  )
myframe

     강남구  은평구  마포구  용산구
김구    10   20   30   40
이봉창   50   60   70   80
안중근   90  100  110  120
윤봉길  130  140  150  160

In [3]:
result = myframe.iloc[1]
print(result)
type(result)

강남구    50
은평구    60
마포구    70
용산구    80
Name: 이봉창, dtype: int64

pandas.core.series.Series

In [4]:
result = myframe.iloc[[1,3]]
print(result)
type(result)

     강남구  은평구  마포구  용산구
이봉창   50   60   70   80
윤봉길  130  140  150  160

pandas.core.frame.DataFrame

In [5]:
result = myframe.loc[['윤봉길']]
print(result)
type(result)

     강남구  은평구  마포구  용산구
윤봉길  130  140  150  160

pandas.core.frame.DataFrame

In [6]:
result = myframe.loc[['이봉창', '윤봉길']]
result

     강남구  은평구  마포구  용산구
이봉창   50   60   70   80
윤봉길  130  140  150  160

In [7]:
result = myframe.loc[['윤봉길'], ['은평구']] # DataFrame
result

     은평구
윤봉길  140

In [8]:
result = myframe.loc[['김구', '이봉창'], ['용산구', '은평구']]
result

     용산구  은평구
김구    40   20
이봉창   80   60

In [9]:
result = myframe.loc[ myframe['은평구'] <= 100 ]
result

     강남구  은평구  마포구  용산구
김구    10   20   30   40
이봉창   50   60   70   80
안중근   90  100  110  120

In [10]:
result = myframe.loc[ myframe['은평구'] == 100 ]
result

     강남구  은평구  마포구  용산구
안중근   90  100  110  120

In [ ]:
myframe.loc['김구':'안중근', ['용산구']] = 80
myframe

     강남구  은평구  마포구  용산구
김구    10   20   30   80
이봉창   50   60   70   80
안중근   90  100  110   80
윤봉길  130  140  150  160

In [ ]:
myframe

     강남구  은평구  마포구  용산구
김구    10   20   30   80
이봉창   50   60   70   80
안중근   90  100  110   80
윤봉길  130  140  150  160