In [1]:
import pandas as pd

In [ ]:
dict1 = {'name':['홍길동', '김철수', '박영희'], 'korean': [70, 80, 90]}
df1 = pd.DataFrame(dict1)
df1

  name  korean
0  홍길동      70
1  김철수      80
2  박영희      90

In [ ]:
dict2 = {'name':['김철수', '홍길동', '심수봉'], 'english':[85, 60, 95]}
df2 = pd.DataFrame(dict2)
df2

  name  english
0  김철수       85
1  홍길동       60
2  심수봉       95

In [ ]:
pd.merge(df1, df2, on='name')

  name  korean  english
0  홍길동      70       60
1  김철수      80       85

In [ ]:
print("\n# how='outer' 라고 명시하면 full outer join이다.")
pd.merge(df1, df2, how='outer')

# how='outer' 라고 명시하면 full outer join이다.

  name  korean  english
0  홍길동    70.0     60.0
1  김철수    80.0     85.0
2  박영희    90.0      NaN
3  심수봉     NaN     95.0

In [ ]:
dict3 = {'leftkey':['홍길동', '김철수', '박영희'], 'korean': [70, 80, 90]}
df3 = pd.DataFrame(dict3)
df3

  leftkey  korean
0     홍길동      70
1     김철수      80
2     박영희      90

In [ ]:
dict4 = {'rightkey':['김철수', '홍길동', '심수봉'], 'english':[85, 60, 95]}
df4 = pd.DataFrame(dict4)
df4

  rightkey  english
0      김철수       85
1      홍길동       60
2      심수봉       95

In [ ]:
pd.merge( df3, df4, left_on='leftkey', right_on='rightkey')

  leftkey  korean rightkey  english
0     홍길동      70      홍길동       60
1     김철수      80      김철수       85

In [ ]:
newdf1 = df1.set_index('name')
newdf1

      korean
name
홍길동       70
김철수       80
박영희       90

In [ ]:
newdf2 = df2.set_index('name')
newdf2

      english
name
김철수        85
홍길동        60
심수봉        95

In [ ]:
result = pd.merge(newdf1, newdf2, left_index=True, right_index=True, how='outer', indicator = True)
result

      korean  english      _merge
name
김철수     80.0     85.0        both
박영희     90.0      NaN   left_only
심수봉      NaN     95.0  right_only
홍길동     70.0     60.0        both